In [719]:
import torch
import torch.nn as nn


In [720]:
tens= torch.tensor([0,1]) #this will just return the first and second row of the embedding matrix

emb = nn.Embedding(4, 3, 3, 2)
print(emb.weight)

a = emb(tens)

print( a)


Parameter containing:
tensor([[ 1.9971, -1.3775, -0.1383],
        [-0.4282,  1.2077, -0.9334],
        [-0.8660,  0.7462, -0.5380],
        [ 0.0000,  0.0000,  0.0000]], requires_grad=True)
tensor([[ 1.6437, -1.1337, -0.1138],
        [-0.4282,  1.2077, -0.9334]], grad_fn=<EmbeddingBackward0>)


In [721]:
import numpy as np

position = torch.Tensor([[1,2,3],[4,5,6]])
print(position)
position0 = np.array(position.unsqueeze(0))
print(position0)
position1 = position.unsqueeze(1)
print(position1)
position_1 = position.unsqueeze(-1)
print(position_1)
position_2 = position.unsqueeze(-2)
print(position_2)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[[1. 2. 3.]
  [4. 5. 6.]]]
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])


In [722]:
import torch
import torch.nn as nn



class InputEmbeddings(nn.Module):
    
    def __init__(self, d_model:int, vocab_size : int): #the dimension of the model and the vocab_size
        super().__init__()
        self.d_model = d_model
        self.vocab_size = vocab_size
        self.embedding= nn.Embedding(vocab_size, d_model)

    def forward(self, x):
        return self.embedding(x) * torch.sqrt(torch.tensor(self.d_model, dtype=torch.float32))
    
class PositionalEncoding(nn.Module):

    def __init__(self, d_model: int, seq_len: int, dropout: float ) -> None:
        super().__init__()
        self.d_model = d_model
        self.seq_len = seq_len
        self.dropout = nn.Dropout(p=dropout)

        #create a matrix of siez (seq_len, d_model) 
        pe = torch.zeros(seq_len, d_model)
        position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1)
        print(position)
        print(position.shape)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-4*torch.log(torch.tensor(10.0)) / d_model))
        print(div_term)
        print(div_term.shape)
        print(position * div_term)
        
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        print(pe)
        pe = pe.unsqueeze(0)
        print(pe)



In [723]:
posi_embed = PositionalEncoding(4, 8, 0.1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
torch.Size([8, 1])
tensor([1.0000, 0.0100])
torch.Size([2])
tensor([[0.0000, 0.0000],
        [1.0000, 0.0100],
        [2.0000, 0.0200],
        [3.0000, 0.0300],
        [4.0000, 0.0400],
        [5.0000, 0.0500],
        [6.0000, 0.0600],
        [7.0000, 0.0700]])
tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0100,  0.9999],
        [ 0.9093, -0.4161,  0.0200,  0.9998],
        [ 0.1411, -0.9900,  0.0300,  0.9996],
        [-0.7568, -0.6536,  0.0400,  0.9992],
        [-0.9589,  0.2837,  0.0500,  0.9988],
        [-0.2794,  0.9602,  0.0600,  0.9982],
        [ 0.6570,  0.7539,  0.0699,  0.9976]])
tensor([[[ 0.0000,  1.0000,  0.0000,  1.0000],
         [ 0.8415,  0.5403,  0.0100,  0.9999],
         [ 0.9093, -0.4161,  0.0200,  0.9998],
         [ 0.1411, -0.9900,  0.0300,  0.9996],
         [-0.7568, -0.6536,  0.0400,  0.9992],
         [-0.9